base32.o: base32.c common.h config.h casts.h debug.h compat.h base32.h
cobs.o: cobs.c cobs.h common.h config.h casts.h debug.h compat.h
compat.o: compat.c compat.h common.h config.h casts.h debug.h append.h \
  nettools.h net_addr.h
connection.o: connection.c connection.h common.h config.h casts.h debug.h \
  compat.h event_source.h net_addr.h nettools.h mem.h oop.h
debug.o: debug.c debug.h common.h config.h casts.h compat.h
dns.o: dns.c dns.h common.h config.h casts.h debug.h compat.h net_addr.h
event_source.o: event_source.c event_source.h common.h config.h casts.h \
  debug.h compat.h event_watcher.h mem.h oop.h
event_watcher.o: event_watcher.c event_watcher.h common.h config.h \
  casts.h debug.h compat.h event_source.h oop.h
ggep.o: ggep.c ggep.h common.h config.h casts.h debug.h compat.h cobs.h \
  append.h nettools.h net_addr.h
guid.o: guid.c guid.h common.h config.h casts.h debug.h compat.h \
  hashtable.h mem.h nettools.h net_addr.h
hashlist.o: hashlist.c hashlist.h common.h config.h casts.h debug.h \
  compat.h node.h mem.h
hashtable.o: hashtable.c hashtable.h common.h config.h casts.h debug.h \
  compat.h mem.h
list.o: list.c mem.h common.h config.h casts.h debug.h compat.h list.h \
  node.h
mem.o: mem.c mem.h common.h config.h casts.h debug.h compat.h
nettools.o: nettools.c nettools.h common.h config.h casts.h debug.h \
  compat.h net_addr.h append.h base32.h
node.o: node.c node.h common.h config.h casts.h debug.h compat.h mem.h
snode.o: snode.c snode.h common.h config.h casts.h debug.h compat.h mem.h
